### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/containerpilot-ui#1]
@moretea I tried to run locally the dev branch using your instructions, but the main panel does not want to load. In console I get

```
Error: Not found
    at /pilot-ui/src/server.js:28:15
    at Layer.handle [as handle_request] (/pilot-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/pilot-ui/node_modules/express/lib/router/index.js:312:13)
    at /pilot-ui/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/pilot-ui/node_modules/express/lib/router/index.js:330:12)
    at next (/pilot-ui/node_modules/express/lib/router/index.js:271:10)
    at /pilot-ui/node_modules/express/lib/router/index.js:618:15
    at next (/pilot-ui/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/pilot-ui/node_modules/express/lib/router/index.js:176:3)
    at router (/pilot-ui/node_modules/express/lib/router/index.js:46:12)
```

it's not something critical, just wanted to see how it works.

**Comment by wolfmanzeroua** [comment]
This error occurs when the server unable to connect to the consul with data specified in the environment variables. You need verify IP and port by using the "docker inspect ..." and set new data in environment variables.

**Comment by moretea** [comment]
@lguminski see the updated instructions in `README.md`. It contains steps to set up the wordpress example.
